version: "3.9"

services:
  bot:
    build: .
    container_name: wb_price_bot
    restart: always
    env_file: .env
    depends_on:
      - db
    volumes:
      - .:/app
    command: >
      sh -c "
      echo 'Waiting for DB...' &&
      sleep 5 &&
      python -m main
      "

  db:
    image: postgres:16-alpine
    container_name: wb_postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-botuser}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-botpass}
      POSTGRES_DB: ${POSTGRES_DB:-wb_bot}
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./migrations/schema.sql:/docker-entrypoint-initdb.d/schema.sql:ro

volumes:
  pg_data:
